# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-29 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=20, unique=True)),
                ('g_date', models.DateField(default='2018-01-24')),
                ('g_num', models.IntegerField(default=0)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20)),
                ('s_age', models.IntegerField()),
                ('s_gender', models.BooleanField()),
                ('isdelete', models.BooleanField(default=False)),
                ('s_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Grades')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
